### ISSUE TITLE
Problems starting setup.py

### ISSUE THREAD

**Issue by mortaca** [hfaran/raspberry-cereal#14] opened 2016-10-25 17:05 UTC
I have python 2.7 , libudev-dev, RPi.GPIO and uinput,I found a mistake in the install.bash calling li**d**udev-dev.
When I run setup.py tells me the following.

> $ sudo python setup.py install
> Traceback (most recent call last):
>   File "setup.py", line 2, in <module>
>     from raspberry_cereal.constants import CONFIG_PATH, CONFIG_DIR
>   File "/home/pi/cereal/raspberry_cereal/__init__.py", line 15, in <module>
>     from raspberry_cereal.validate_cfg import main as validate_config
>   File "/home/pi/cereal/raspberry_cereal/validate_cfg.py", line 25
>     assert hasattr(GPIO, config.get(section, option)),
>                                                      ^
> SyntaxError: invalid syntax

**Comment by hfaran** [comment] 2016-10-26 09:54
Resolved by 78637c73988fcee49c878b3e087a86874a2facd1

**Comment by hfaran** [comment] 2016-10-26 09:55
@mortaca Please try the latest changes. I actually had them sitting on disk locally (for maybe over a year), and totally forgot to push them.

**Closed by hfaran** 2016-10-26 09:54 UTC

**Comment by mortaca** [comment] 2016-10-26 11:11
I modified files and it worked in part, had another syntax error, I deleted everything and return to unzip the zip, edit and delete backup files and tells me this.

> Traceback (most recent call last):
>   File "setup.py", line 2, in <module>
>     from raspberry_cereal.constants import CONFIG_PATH, CONFIG_DIR
>   File "/home/pi/raspberry-cereal-master/raspberry_cereal/__init__.py", line 15, in <module>
>     from raspberry_cereal.validate_cfg import main as validate_config
>   File "/home/pi/raspberry-cereal-master/raspberry_cereal/validate_cfg.py", line 25
>     assert hasattr(GPIO, config.get(section, option)),
>                                                      ^
> SyntaxError: invalid syntax

Run your program is very important to launch a very interesting project, thanks for the help.

**Comment by hfaran** [comment] 2016-10-26 11:17
That's the exact same error. Did you not pull the latest changes?

**Comment by mortaca** [comment] 2016-10-26 11:24
If they are modified. The first time it looked like it was installed correctly, I wonder if I wanted to replace the configuration file, but after the program did not work, I deleted everything returned to decompress, modified again and no longer works, please if you can do the test down the zip only modify these two files and run to see if you have the same problem, thanks.

**Comment by hfaran** [comment] 2016-10-26 11:36
> If they are modified. The first time it looked like it was installed correctly, I wonder if I wanted to replace the configuration file, but after the program did not work, I deleted everything returned to decompress, modified again and no longer works, please if you can do the test down the zip only modify these two files and run to see if you have the same problem, thanks.

I'm sorry but I didn't really understand any of this. I'm assuming English isn't your first language. Can you re-write this to describe very clear what issues you're experiencing and a very clear list of steps to reproduce the issue?
Additionally, what does your hardware setup look like?
Also, I notice you mention the configuration file: yes you **definitely need to modify the config file** after you've installed raspberry-cereal. Remember to modify it at the correct location as per the instructions in the [Usage section of the README](https://github.com/hfaran/raspberry-cereal#usage).

**Comment by mortaca** [comment] 2016-10-26 22:05
Yes, sorry for using the translator.
I've done work, the problem was to copy the new text and remove the "+" symbols, there is also a blank space and this had not been removed.

Not sure if you have understood hehe.

**Comment by mortaca** [comment] 2016-11-01 09:07
There is an error in the readme instead of 
`$ sudo raspberry_cereal &`
 should be
`$ sudo raspberry-cereal &`
After this gives me an error in the string but it should be by the integrated I am using it is not 74HC165N

> [WAIT] Setting up...
> Traceback (most recent call last):
>   File "/usr/local/bin/raspberry-cereal", line 9, in <module>
>     load_entry_point('raspberry-cereal==1.0.1', 'console_scripts', 'raspberry-cereal')()
>   File "build/bdist.linux-armv7l/egg/raspberry_cereal/__init__.py", line 37, in main
>   File "build/bdist.linux-armv7l/egg/raspberry_cereal/validate_cfg.py", line 28, in main
>   File "/usr/lib/python2.7/ast.py", line 80, in literal_eval
>     return _convert(node_or_string)
>   File "/usr/lib/python2.7/ast.py", line 79, in _convert
>     raise ValueError('malformed string')
> ValueError: malformed string

**Comment by hfaran** [comment] 2016-11-01 09:24
Ah, yes that is a typo.

With regards to the shift register, if you're not using the 74HC165N, you'll need to add support for the one you're using (MCP23S17); you need to read the datasheet and write your own module for it as I've done. Unfortunately, I can't do it as I don't have the that register.

**Comment by mortaca** [comment] 2016-11-01 09:36
Ok, I will use 74HC165N, then I have to leave

> pLoadPin: 23
> dataPin: 24
> clockPin: 25

These values do not correspond to the BCM pins MISO & SCLK in aRPi3.

If you want I can send you a few MCP23S17 for you to do tests.

**Comment by hfaran** [comment] 2016-11-01 09:42
> If you want I can send you a few MCP23S17 for you to do tests.

Thanks for the offer, but unfortunately, I don't have time to work this on at the current time.

If it's easy for you to pick up some 74HC165N ICs, then I would recommend doing that as it's probably the easiest.

I'm not sure how different the MCP23S17 would be but if it's still a shift register, I think it should operate similarly. I would encourage you to read the datasheet and write a new python module to add to this project so support can be added for both these ICs. If you don't feel comfortable doing that, then feel free to use the 74HC IC.

As for the keymapping, if you know what the new values are for the aRPi3, you should change them in your local config file. I believe I developed this against the RPi Model B so the pins probably changed since then.

**Comment by mortaca** [comment] 2016-11-02 12:00
I have already installed the 74HC165N and the same error as before.
Vcc 3.3v with 10k resistors on the parallel inputs
Q7=GPIO9 PL=GPIO10 CP=GPIO11
I can use any GPIO pin that does not match the SPI port?
Documentation on selected pins do not match the SPI port model B, but in other examples of internet use SPI port pins.

**Comment by mortaca** [comment] 2016-11-03 10:20
You have to put the GPIO pins in some way? Or cereal auto configure?
I have them with nothing assigned.

>   GPIO 09: level=0 fsel=0 alt=  func=INPUT
>   GPIO 10: level=0 fsel=0 alt=  func=INPUT
>   GPIO 11: level=0 fsel=0 alt=  func=INPUT

Please some help to put the program into operation.

**Comment by mortaca** [comment] 2016-11-04 17:26
I have used this scheme but 3.3v Vcc is correct?

http://2.bp.blogspot.com/-YHxnKXc77ac/VpOHe62soRI/AAAAAAAAApc/Ln7M8sWUzls/s1600/Shift_Input.jpg
